const mongoose = require('mongoose');
const requireLogin = require('../middlewares/requireLogin');
const requireCredits = require('../middlewares/requireCredits');
const Mailer = require('../services/Mailer');
const surveyTemplate = require('../services/emailTemplates/surveyTemplate');

//Model class to create an instance of a survey
const Survey = mongoose.model('surveys');

//Arguments mut be in the proper order to run properly
module.exports = app => {
    app.get('/api/surveys/thanks', (req, res) => {
        res.send('Thanks for voting!');
    });

    //Not calling the function - simply telling express app object that we have a function it should checkout if a user is logged in
    app.post('/api/surveys', requireLogin, requireCredits, async (req, res) => {
        //ES6 destructuring to pull out certain properties
        const { title, subject, body, recipients } = req.body;
        //lowercase since it is an instance
        const survey = new Survey({
            //Keys identical to properties so only have to list singularly
            title,
            subject,
            body,
            //Array of objects containing email addresses - since we return only one JS exression we don't need outer curly braces and return keyword
            recipients: recipients.split(',').map(email => ({ email: email.trim() })), 
            //Links current user to survey - id automatically generated by Mongo
            _user: req.user.id,
            dateSent: Date.now()
        });

        //Send the Email 
        const mailer = new Mailer(survey, surveyTemplate(survey));
        
        //Watch if anything goes wrong with these statements, catch requests and send error  
        try {
            await mailer.send();
            //saves survey to the database
            await survey.save();
            //Subracts credits after survey sent 
            req.user.credits -= 1;
            const user = await req.user.save();
            //send back updated user model
            res.send(user)
        } catch (err) {
            res.status()
        }   
    });
};

//This creates an instance of a survey in memory - it does not yet persist it yet to the database 