const mongoose = require('mongoose');
const requireLogin = require('../middlewares/requireLogin');
const requireCredits = require('../middlewares/requireCredits');

//Model class to create an instance of a survey
const Survey = mongoose.model('surveys');

//Arguments mut be in the proper order to run properly
module.exports = app => {
    //Not calling the function - simply telling express app object that we have a function it should checkout if a user is logged in
    app.post('/api/surveys', requireLogin, requireCredits, (req, res) => {
        //ES6 destructuring to pull out certain properties
        const { title, subject, body, recipients } = req.body;
        //lowercase since it is an instance
        const survey = new Survey({
            //Keys identical to properties so only have to list singularly
            title,
            subject,
            body,
            //Array of objects containing email addresses - since we return only one JS exression we don't need outer curly braces and return keyword
            recipients: recipients.split(',').map(email => ({ email: email.trim() })), 
            //Links current user to survey - id automatically generated by Mongo
            _user: req.user.id,
            dateSent: Date.now()
        });
    });
};

//This creates an instance of a survey in memory - it does not yet persist it yet to the database 